embed_assets: on

javascripts:
  framework:
    - public/52framework/js/modernizr-1.1.min.js
    - public/javascripts/jquery.1.4.4.js
    - public/javascripts/jquery-ui.1.8.7.js
    - public/javascripts/rails.js
  application:
    - public/javascripts/application.js

stylesheets:
  framework:
    - public/52framework/css/reset.css
    - public/52framework/css/css3.css
    - public/52framework/css/general.css
    - public/52framework/css/grid.css
    - public/stylesheets/css3-action-framework.css
  application:
    - public/stylesheets/messages.css
    - public/stylesheets/helpdeck.css