embed_assets: on

javascripts:
  framework:
    - public/52framework/js/modernizr-1.1.min.js
    - https://ajax.googleapis.com/ajax/libs/jquery/1.4.4/jquery.min.js
    - https://ajax.googleapis.com/ajax/libs/jqueryui/1.8.7/jquery-ui.min.js
    - public/javascripts/rails.js
  application:
    - public/javascripts/application.js

stylesheets:
  framework:
    - public/52framework/css/reset.css
    - public/52framework/css/css3.css
    - public/52framework/css/general.css
    - public/52framework/css/grid.css
  application:
    - public/stylesheets/css3-action-framework.css
    - public/stylesheets/messages.css
    - public/stylesheets/helpdeck.css